/******************************************************************************
 * Module 11 final-project baseline: LHCb-style MVA trigger inference
 *
 * A single-hidden-layer fully connected neural network (ReLU + sigmoid),
 * the kind used in the LHCb Allen trigger to classify events. This file is a
 * DELIBERATELY UNOPTIMIZED, correct baseline. Your job (with an AI assistant)
 * is to make it faster WITHOUT breaking correctness.
 *
 * This is the "correct but slow" starting point for the 5-phase loop:
 *   SPECIFY -> GENERATE -> PREDICT -> VERIFY -> DIAGNOSE
 *
 * Self-contained: no external data, no JSON, no CMake. Compile with:
 *   nvcc -O3 -arch=native mva_infer_baseline.cu -o mva_infer_baseline
 * Run:
 *   ./mva_infer_baseline                # default 20,000,000 events
 *   ./mva_infer_baseline 50000000       # custom event count
 *
 * The program prints throughput (events/sec) and a PASS/FAIL correctness
 * check against a CPU reference. Treat throughput as the project metric and
 * the correctness check as a hard gate: an optimization that fails the check
 * does not count.
 *
 * DO NOT edit this file to "win". Copy it, and have the AI produce optimized
 * variants (e.g. mva_infer_v1.cu, mva_infer_v2.cu). Keep this baseline as your
 * reference version and your speedup denominator.
 *****************************************************************************/

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <chrono>
#include <random>

// Network shape (fixed at compile time, mirrors the Allen single-layer FCNN).
#define NUM_INPUT 4
#define NUM_NODE  8

// ---------------------------------------------------------------------------
// Model parameters. In the real trigger these come from a trained model; here
// we generate them from a fixed seed so the run is reproducible and needs no
// external data file.
// ---------------------------------------------------------------------------
struct Model {
    float mean[NUM_INPUT];
    float istd[NUM_INPUT];              // 1 / std, precomputed on the host
    float weights1[NUM_NODE][NUM_INPUT];
    float bias1[NUM_NODE];
    float weights2[NUM_NODE];
    float bias2;
};

static void fill_model(Model& m, unsigned seed) {
    std::mt19937 rng(seed);
    std::uniform_real_distribution<float> w(-1.0f, 1.0f);
    std::uniform_real_distribution<float> s(0.5f, 1.5f);
    for (int i = 0; i < NUM_INPUT; ++i) {
        m.mean[i] = w(rng);
        m.istd[i] = 1.0f / s(rng);
    }
    for (int n = 0; n < NUM_NODE; ++n) {
        for (int i = 0; i < NUM_INPUT; ++i) m.weights1[n][i] = w(rng);
        m.bias1[n]    = w(rng);
        m.weights2[n] = w(rng);
    }
    m.bias2 = w(rng);
}

// ---------------------------------------------------------------------------
// CPU reference implementation. This is the correctness REFERENCE. The GPU
// result must match this to within a small tolerance.
// ---------------------------------------------------------------------------
static float evaluate_cpu(const Model& m, const float* x) {
    float in[NUM_INPUT];
    for (int i = 0; i < NUM_INPUT; ++i)
        in[i] = (x[i] - m.mean[i]) * m.istd[i];

    float h[NUM_NODE];
    for (int n = 0; n < NUM_NODE; ++n) {
        float acc = m.bias1[n];
        for (int i = 0; i < NUM_INPUT; ++i)
            acc += in[i] * m.weights1[n][i];
        h[n] = acc > 0.0f ? acc : 0.0f;         // ReLU
    }

    float out = m.bias2;
    for (int n = 0; n < NUM_NODE; ++n)
        out += h[n] * m.weights2[n];

    return 1.0f / (1.0f + std::exp(-out));       // sigmoid
}

// ---------------------------------------------------------------------------
// GPU baseline kernel: one thread per event, model read from global memory,
// standard (non-fast-math) division and exp. Nothing here is tuned.
// ---------------------------------------------------------------------------
__global__ void infer_baseline(const Model* m,
                               const float* input,   // [num_events * NUM_INPUT]
                               float* output,        // [num_events]
                               int num_events) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= num_events) return;

    float in[NUM_INPUT];
    for (int i = 0; i < NUM_INPUT; ++i)
        in[i] = (input[idx * NUM_INPUT + i] - m->mean[i]) * m->istd[i];

    float h[NUM_NODE];
    for (int n = 0; n < NUM_NODE; ++n) {
        float acc = m->bias1[n];
        for (int i = 0; i < NUM_INPUT; ++i)
            acc += in[i] * m->weights1[n][i];
        h[n] = acc > 0.0f ? acc : 0.0f;
    }

    float out = m->bias2;
    for (int n = 0; n < NUM_NODE; ++n)
        out += h[n] * m->weights2[n];

    output[idx] = 1.0f / (1.0f + expf(-out));
}

static void check_cuda(cudaError_t e, const char* what) {
    if (e != cudaSuccess) {
        std::fprintf(stderr, "CUDA error at %s: %s\n", what, cudaGetErrorString(e));
        std::exit(1);
    }
}

int main(int argc, char** argv) {
    int num_events = (argc > 1) ? std::atoi(argv[1]) : 20'000'000;
    if (num_events <= 0) num_events = 20'000'000;

    std::printf("MVA inference baseline\n");
    std::printf("  events      : %d\n", num_events);
    std::printf("  input size  : %d\n", NUM_INPUT);
    std::printf("  hidden nodes: %d\n", NUM_NODE);

    Model model;
    fill_model(model, 12345u);

    // Host input: reproducible random "detector features".
    std::vector<float> h_input((size_t)num_events * NUM_INPUT);
    {
        std::mt19937 rng(2024u);
        std::uniform_real_distribution<float> d(-3.0f, 3.0f);
        for (auto& v : h_input) v = d(rng);
    }
    std::vector<float> h_output(num_events);

    // Device allocations (plain cudaMalloc / cudaMemcpy — no unified memory).
    Model* d_model = nullptr;
    float* d_input = nullptr;
    float* d_output = nullptr;
    check_cuda(cudaMalloc(&d_model, sizeof(Model)), "malloc model");
    check_cuda(cudaMalloc(&d_input, h_input.size() * sizeof(float)), "malloc input");
    check_cuda(cudaMalloc(&d_output, (size_t)num_events * sizeof(float)), "malloc output");

    // Time the full round trip: H2D copy + kernel + D2H copy.
    check_cuda(cudaDeviceSynchronize(), "warmup sync");
    auto t0 = std::chrono::high_resolution_clock::now();

    check_cuda(cudaMemcpy(d_model, &model, sizeof(Model), cudaMemcpyHostToDevice), "H2D model");
    check_cuda(cudaMemcpy(d_input, h_input.data(), h_input.size() * sizeof(float),
                          cudaMemcpyHostToDevice), "H2D input");

    int block = 256;
    int grid  = (num_events + block - 1) / block;
    infer_baseline<<<grid, block>>>(d_model, d_input, d_output, num_events);
    check_cuda(cudaGetLastError(), "kernel launch");

    check_cuda(cudaMemcpy(h_output.data(), d_output, (size_t)num_events * sizeof(float),
                          cudaMemcpyDeviceToHost), "D2H output");
    check_cuda(cudaDeviceSynchronize(), "final sync");

    auto t1 = std::chrono::high_resolution_clock::now();
    double secs = std::chrono::duration<double>(t1 - t0).count();
    double throughput = num_events / secs;

    std::printf("  time (H2D+kernel+D2H): %.3f ms\n", secs * 1e3);
    std::printf("  throughput           : %.2f M events/sec\n", throughput / 1e6);

    // -------------------- correctness gate --------------------
    // Spot-check a sample of events spread across the WHOLE range against the
    // CPU reference, always including the last event. Sampling the tail as well
    // as the head is what makes a non-multiple-of-block-size run actually catch
    // dropped bounds checks and grid-stride off-by-one bugs (those corrupt the
    // LAST events, not the first).
    const int sample = num_events < 10000 ? num_events : 10000;
    const int stride = num_events / sample;   // >= 1; spreads the sample over [0, num_events)
    double max_abs_err = 0.0;
    bool range_ok = true;
    auto check_event = [&](int i) {
        float ref = evaluate_cpu(model, &h_input[(size_t)i * NUM_INPUT]);
        double err = std::fabs((double)ref - (double)h_output[i]);
        if (err > max_abs_err) max_abs_err = err;
        if (h_output[i] < 0.0f || h_output[i] > 1.0f) range_ok = false;
    };
    for (int s = 0; s < sample; ++s) check_event(s * stride);
    check_event(num_events - 1);   // always test the very last event (the tail)
    const double tol = 1e-5;
    bool pass = (max_abs_err <= tol) && range_ok;
    std::printf("  max abs error vs CPU : %.3e (tol %.1e)\n", max_abs_err, tol);
    std::printf("  sigmoid range [0,1]  : %s\n", range_ok ? "ok" : "VIOLATED");
    std::printf("  RESULT               : %s\n", pass ? "PASS" : "FAIL");

    cudaFree(d_model);
    cudaFree(d_input);
    cudaFree(d_output);
    return pass ? 0 : 1;
}
